### ISSUE TITLE
无法解码

### ISSUE THREAD

**Issue by Cathgao** [MoebutagataShiozakana/CGSSAssetsDownloader#1]
长时间高占用，但没有文件输出。
![default](https://user-images.githubusercontent.com/21031564/36540611-066d1762-1816-11e8-8f91-6bf6cb49c1b4.PNG)

**Comment by toyobayashi** [comment]
我这里也是没问题的。manifest_1003xxxx.db有出来吗？mishiro已经发布新版修复了空格问题。

**Comment by toyobayashi** [comment]
@Cathgao 试一下1.8，应该是路径问题
